### PR TITLE
Added an api method to unload plugins fully from proxy.

### PR DESCRIPTION
**Pull request by abhiram555**
So yeah basically i added a method to unload plugin fully from the proxy

### CODE REVIEW

**Comment by abhiram555** [comment]
@linsaftw could you review this please?

**Comment by linsaftw** [comment]
> @linsaftw could you review this please?

Why not implementing this on BungeeCord?

**Comment by abhiram555** [comment]
> > @linsaftw could you review this please?
> 
> Why not implementing this on BungeeCord?

well a pr is open on BungeeCord for some reason I don't think md_5 wants this in bungeecord. so yeah I thought why not open pr on forks

**Review by LewUwU — CHANGES_REQUESTED** [review]
Follow BungeeCord Checkstyle format

**Comment by abhiram555** [comment]
> Follow BungeeCord Checkstyle format

everything should be good now!

**Comment by Luccboy** [comment]
I think it would be better to move your changes into one single patch file instead of having 3

**Comment by linsaftw** [comment]
Marked as invalid because of wrong patch implementation. Please fix your commits.

**Comment by abhiram555** [comment]
everything should be good now :)

**Comment by Luccboy** [comment]
You still have 2 patch files instead of 1

**Comment by abhiram555** [comment]
> You still have 2 patch files instead of 1

ah forgot about that, will fix it

**Comment by abhiram555** [comment]
well i think keeping it as 2 commits would be good. git is giving me hard time while i am trying to merge my 2 commits lol

**Comment by abhiram555** [comment]
Done :)

**Pull request merged**
