### PR TITLE
Upstream Waterfall

### PR DESCRIPTION
**Pull request by uRyanxD**

### CODE REVIEW

**Comment by xIsm4** [comment]
> _ No description provided. _

FlameCord already does that i thing, then this upstream should be skipped i guess.

**Comment by linsaftw** [comment]
Will this compile?

**Comment by uRyanxD** [comment]
It compiled with no problems for me, however, I agree with xIsm4 to skip this upstream.

**Comment by linsaftw** [comment]
Closed. Other more recent upstream update has been requested.

**Pull request closed without merging**
