### PR TITLE
Updated Upstream (Waterfall)

### PR DESCRIPTION
**Pull request by Luccboy**
Upstream has released updates that appear to apply and compile correctly.
This update has not been tested by 2LStudios and as with ANY update, please do your own testing

Waterfall Changes:
9719e25 Temp disable protocol limits for 1.19
9b0080a Fix crash on startup (#743)
958ae29 Updated Upstream (BungeeCord) (#741)
29f1cfb Improve login state transition
a44c78a Various library bumps

### CODE REVIEW

**Comment by linsaftw** [comment]
We will merge and test later.

**Comment by linsaftw** [comment]
https://mclogs.minestrator.com/ESjHlAA Errors on startup. We are reverting.

**Comment by Luccboy** [comment]
> https://mclogs.minestrator.com/ESjHlAA Errors on startup. We are reverting.
> 
> EDIT: This is BungeeGuard. Lets review the situation before reverting.

Yeah, the sane issue was also reported to Waterfall: https://github.com/PaperMC/Waterfall/issues/745

**Comment by linsaftw** [comment]
Not only that but there are join errors too. Reverting.

**Comment by Luccboy** [comment]
Strange, I dont have any errors:
image
Which version of spigot are you using?

**Comment by linsaftw** [comment]
> Strange, I don't have any errors: image Which version of spigot are you using? Do you use any plugins? What's your client version?

No plugins. 1.8. Might be config issue?

**Pull request merged**
