### PR TITLE
Updated Upstream (Waterfall)

### PR DESCRIPTION
**Pull request by guacaplushy**
Upstream has released updates that appears to apply and compile correctly.
This update has not been tested by 2LStudios and as with ANY update, please do your own testing

Waterfall Changes:
9137560 Updated Upstream (BungeeCord) (#678)
7196e44 Don't spam github actions log with maven progress (#662)

### CODE REVIEW

**Comment by Luccboy** [comment]
Did you rebuild the patches?

**Comment by linsaftw** [comment]
I think he might have forgot again. Or maybe it doesn't rebuild because it fails.

**Comment by guacaplushy** [comment]
Ive tried running ./flamecord rbp but it didnt seem to do anything

**Comment by linsaftw** [comment]
> Ive tried running ./flamecord rbp but it didnt seem to do anything

Alright maybe it seems nothing that the new waterfall update touched affects flamecord. I will test this and update if working.

**Comment by Luccboy** [comment]
@linsaftw There are merge conflicts:
image

**Comment by linsaftw** [comment]
> @linsaftw There are merge conflicts:
> image

Sorry I missed those. Do you want me to fix them or you will open a PR?

**Comment by Luccboy** [comment]
I can try to fix them if you want :)

**Comment by linsaftw** [comment]
> I can try to fix them if you want :)

Don't worry ill do a commit with the patches :)

**Pull request merged**
