### PR TITLE
Added process for workflows in Github Actions

### PR DESCRIPTION
**Pull request by 4drian3d**
Tested and works correctly in JDK 8, 11 and 16.
This will perform a test on each push on the branch master or pull request that is made, to check its correct compilation and to deliver an artifact on each action and for each Java version (8, 11 and 16).

### CODE REVIEW

**Comment by 4drian3d** [comment]
Java 16 will be standard as of Minecraft 1.17+ https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a

**Comment by linsaftw** [comment]
> Java 16 will be standard as of Minecraft 1.17+ https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a

BungeeCord is completely standalone so that won't affect.

**Comment by 4drian3d** [comment]
It is only to check that it works in Java 16, since, after the change, many people will start using Java 16 for servers and proxies commonly.

**Comment by linsaftw** [comment]
Okay its not merged, how does it works exactly?

**Comment by 4drian3d** [comment]
If it works correctly, you will see in the Actions tab of the repository: https://github.com/2lstudios-mc/FlameCord/actions/runs/845043206 that a test build has been started to check that Flamecord is compiled correctly, and if it is the case, it will deliver artifacts with each JDK version with which it has been compiled. In .github/workflows/flamecord-build.yml I have left comments about the function of each action to be performed on each new code change or pull request.

**Comment by 4drian3d** [comment]
This can be useful, for example, if the latest version of FlameCord has a bug, and someone reports it, but the fix is in the repository, then you can cite the link to the FlameCord compilation with the corresponding fix, until a full version is released.

**Pull request merged**
